apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    user: postgres

    jsonData:
      database: sayargyi
      sslmode: disable
      postgresVersion: 16

    secureJsonData:
      password: postgres

    isDefault: true